# Generated by Django 4.2.16 on 2026-08-15 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("equipment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking_ref",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated: BK-2026-0001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("request_date", models.DateField(auto_now_add=True)),
                ("required_from", models.DateField()),
                ("required_till", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("issued", "Issued"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Student's note/reason for request",
                        null=True,
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True, help_text="Staff's reason for rejection", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff or Admin who approved/rejected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        help_text="Student or Faculty who made the request",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expected_return",
                    models.DateField(help_text="= booking.required_till"),
                ),
                ("actual_return", models.DateTimeField(blank=True, null=True)),
                (
                    "condition_on_return",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("good", "Good"),
                            ("damaged", "Damaged"),
                            ("lost", "Lost"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issue_log",
                        to="bookings.booking",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        help_text="Staff who issued the equipment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "returned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Staff who received the returned equipment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="received_returns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue Log",
                "verbose_name_plural": "Issue Logs",
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_description", models.TextField()),
                (
                    "quantity_affected",
                    models.PositiveIntegerField(
                        default=1, help_text="How many units are damaged/lost"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_records",
                        to="equipment.equipment",
                    ),
                ),
                (
                    "issue_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which return triggered this",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance",
                        to="bookings.issuelog",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
